### ISSUE TITLE
Could not find com.google.firebase:firebase-core:11.4.2

### ISSUE THREAD

**Issue by rlakenvelt** [NativeScript/push-plugin#144] opened 2017-10-29 08:43 UTC
I suddenly have the following error while doing a 'tns build android' on a project that has build many times without errors:

A problem occurred configuring root project 'MyApp'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.google.firebase:firebase-core:11.4.2.
     Required by:
         project :

Also older versions of the project that have build without error have the same problem now.
I can also reproduce the error by creating a small project from scratch:

- tns create MyApp
- cd MyApp
- tns plugin add nativescript-push-notifications
- tns build android

I think it must be something in the configuration of my machine but I am not aware of any recent change. I also get the same error on our continuous integration machine which definitely did not have any configuration change.
IOS builds fine.

I tried updating the application toolkit and google play services SDK but without succes.
Also tried to upgrade from tns 3.2.0 to 3.3., also no succes.

MacOS 10.12.6
tns 3.3.0

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MyApp",
    "tns-android": {
      "version": "3.2.0"
  },
  "dependencies": {
    "nativescript-push-notifications": "^0.1.4",
    "nativescript-theme-core": "~1.0.2",
    "tns-core-modules": "~3.2.0"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11"
  }
}
```

**Comment by ickata** [comment] 2017-10-29 18:59
Hey @rlakenvelt , it is not your machine, I have the same problem, and it appears that there are other ppl having the same issue: NativeScript/NativeScript#5004

Let's hope that they will fix it soon, however I have a feeling that this plugin has been discontinued...

**Comment by trunkovich** [comment] 2017-10-30 08:57
Same problem on both MacOS and Windows for Android platform.

**Comment by radeva** [comment] 2017-10-30 11:10
Hi @manigorsh, @ickata, @shayfriedman, @trunkovich , @ickata, @rlakenvelt 

we identified the issue is caused by the upgraded gradle which [doesn't support '+' versions anymore](https://developer.android.com/studio/releases/gradle-plugin.html#updating-plugin). 

> Caution: You should not use dynamic dependencies in version numbers, such as 'com.android.tools.build:gradle:2.+'. Using this feature can cause unexpected version updates and difficulty resolving version differences.

We'll provided a fix later today. It's already merged in `master`.

Best regards,
Veselina

**Closed** 2017-10-30 11:39 UTC
Labels: S:High

**Comment by rlakenvelt** [comment] 2017-10-30 11:41
I can confirm that the merge from @radeva  fixes the issue for me. Thanks for the fast response!

**Comment by alexmeia** [comment] 2017-10-30 12:23
Same problem here. Due to compatibility problems with the nativescritp-google-maps-sdk-plugin, when I setup the project I forced both com.google.android.gms:play-services-maps and com.google.firebase:firebase-messaging to use version 11.4.0 in app.gradle file (inside app/App_Resources/Android folder):

`project.ext {
    firebaseMessagingVersion = "11.4.0"
    googlePlayServicesVersion = "11.4.0"
}  `

Everything worked fine until two days ago, and now I am not able to build the project for Android.
The question, obviously, is: who looks for version 11.4.2 of firebase-core? And why?

**Comment by alexmeia** [comment] 2017-10-30 12:32
I confirm that version 0.1.5 fixes the issue form me too. Thanks @radeva!

**Comment by ickata** [comment] 2017-10-30 20:05
Confirm as fixed. Thank you {N} team for the fast response!

**Comment by joyindai2015** [comment] 2018-04-24 05:26
FCM work in cordova 7.1.0 and android 6.4

**Comment by joyindai2015** [comment] 2018-04-24 05:27
I have face problem

**Comment by joyindai2015** [comment] 2018-04-24 05:27
buil.gradle not properly work for ma
