### ISSUE TITLE
Can't compile fresh new project

### ISSUE THREAD

**Issue by arielnmz** [NativeScript/push-plugin#173] opened 2018-01-03 00:14 UTC
I don't know wether this is a gradle, nativescript or push-plugin issue but if you create a new project with:

`tns create <project-name>`

And then install the plugin with:

`tns plugin add nativescript-push-plugin`

then do `tns platform add android` and `tns build android`, the build will fail with the following message:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/ariel/nstest/pushtest/platforms/android/build.gradle' line: 11

* What went wrong:
Could not compile build file '/home/ariel/nstest/pushtest/platforms/android/build.gradle'.
> startup failed:
  build file '/home/ariel/nstest/pushtest/platforms/android/build.gradle': 11: expecting anything but ''\n''; got it anyway @ line 11, column 51.
     roid.tools.build:gradle:2.3.3'
                                   ^
  
  1 error
```

The erroneous file looks like this:

```
buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.google.gms:google-services:3.1.1"
		classpath "com.android.tools.build:gradle:2.3.3'
    }
}
```

And of course changing that ```'``` for a ```"``` works, as mentioned here [#165 (comment)](https://github.com/NativeScript/push-plugin/issues/165#issuecomment-354615340), but then it fails with the following message:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'pushtest'.
> Configuration with name 'compile' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

But you can fix that too, as mentioned [in this other comment on issue #170](https://github.com/NativeScript/push-plugin/issues/170#issuecomment-354722975), however, it will fail again with this one:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processF0DebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /home/ariel/nstest/pushtest/platforms/android/app/src/F0/debug/google-services.json
  /home/ariel/nstest/pushtest/platforms/android/app/src/debug/F0/google-services.json
  /home/ariel/nstest/pushtest/platforms/android/app/src/F0/google-services.json
  /home/ariel/nstest/pushtest/platforms/android/app/src/debug/google-services.json
  /home/ariel/nstest/pushtest/platforms/android/app/src/F0Debug/google-services.json
  /home/ariel/nstest/pushtest/platforms/android/app/google-services.json
```

Despite `google-services.json` being correctly located in `app/App_Resources/Android/`

**Comment by prabudevarrajan1** [comment] 2018-01-03 02:11
Facing the same issue - works fine on tns-android 3.3.1 and not on 3.4.0

**Comment by lini** [comment] 2018-01-03 09:40
This issue should be fixed in the latest release of the plugin - https://github.com/NativeScript/push-plugin/releases/tag/v0.3.0

**Comment by dtopuzov** [comment] 2018-01-03 10:11
Close as duplicate of https://github.com/NativeScript/push-plugin/issues/173

**Closed by dtopuzov** 2018-01-03 10:11 UTC
