### ISSUE TITLE
Android: Push Notification Problems When App in Background

### ISSUE THREAD

**Issue by tomylee001001** [NativeScript/push-plugin#188] opened 2018-01-16 12:08 UTC
i open similar issue about one of my problems earlier and i thought problem was solved with 1.0 release but i was wrong.
i have 2 problems with the plugin.
when sending notifications if app is in foreground "onMessageReceived" kicks in and i can get all the data i sent.if app is close i get a tray icon message and when i click it i can get the data part of my notification with;
application.on(application.resumeEvent, function(args) {
    if (args.android) {
        var act = args.android;
        var intent = act.getIntent();
        var extras = intent.getExtras();
        if (extras) {
            var msg = extras.get('mykey');
        }
    }
});
this works too. 
Now my problems are
1)after you get notification with above code when your app close if you send your app background then foreground manually above code still gets the notification data so how can i differentiate if app is resuming manualy or with clicking the tray message.Do i have to save all notifications to the phone so that i try to look if i process this notification or not. in the short run this can be possible but in the long run with hundreds of messages or thousands of messages send this will be quite a burden for this app.
2)if you send notification when your app is background neither "onMessageReceived" nor "application.resumeEvent" gets the data you are sending. how can we read send data when app is in the background and not close.
thanks for advance.

**Comment by DimitarTachev** [comment] 2018-01-19 15:26
Hi @tomylee001001,

1) You could remove the keys from the Intent after processing them. In this way, you won't get them back when the user manually switches the app between foreground and background modes. In other words, use the following code:

```
    ...
    while (iterator.hasNext()) {
        const key = iterator.next();
        console.log(key + ": " + extras.get(key).toString());
        // clear the used keys in order to avoid getting them back
        // when manually switching the application between background and foreground
        intent.removeExtra(key);
    }
    ...
```
2) When your app is in background or closed, the user should click the notification in order to get its data in the above-mentioned intent.

**Comment by tomylee001001** [comment] 2018-01-22 15:52
hi @DimitarTachev ,

First of all sorry for late reply.

i try  "intent.removeExtra(key);" and it works as you said so my first problem is solved with this code.

For my second problem; i am already trying to read from the intent for notification data. if my app is closed and i tap the notification that intent code work perfectly and i can get my data from it but if my app is in the background instead of closed that intent dont have any data in it.

**Comment by DimitarTachev** [comment] 2018-01-23 16:19
@tomylee001001 

1) I'm glad it helped.

2) That's not the expected behavior. The intent should always contain the notification data in the resume event when you click the notification from the notifications area.
In the Demo app, [we are attaching on the resume event just before the app start](https://github.com/NativeScript/push-plugin/blob/master/demo/app/app.ts#L13) and everything is working as expected. Could you check the intent data using the demo app on your side and update us back?

**Comment by tomylee001001** [comment] 2018-01-24 09:33
@DimitarTachev 
i try the demo aplication and it works but demo application is written with nativescript vanilla and i use nativescript-angular. if you can provide demo application with nativescript-angular i will try that too. Because even though i copied the same code from the demo app to my app i still cant get anything when my app is background and not closed.

**Comment by tomylee001001** [comment] 2018-01-24 11:08
@DimitarTachev 
After playing with demo app a little bit i think i finally found the problem.
if you add android:screenOrientation="portrait" android:launchMode="singleTop" to your main activity in the "AndroidManifest.xml" located in "app\App_Resources\Android" 
notification data dont show in the resume event.
Can you confirm this behavior for the plugin?

**Comment by DimitarTachev** [comment] 2018-01-25 16:56
@tomylee001001, thanks for digging into that. The problematic behavior is caused by the launchMode setting. We are further investigating it with the Nativescript Core Modules team and we will update you back as soon as we have a recommended approach for this scenario.

Meanwhile, you could use [this workaround](https://github.com/NativeScript/push-plugin/issues/179#issuecomment-355738846) suggested by @jogboms or remove the custom launch event which will restart your app on notification click.

**Comment by btulsi-ygrene** [comment] 2018-01-26 00:02
@DimitarTachev 
I am facing the same issue with launchMode="singleTop", and can't be changed as I need this specific launchMode.

Hoping for solution soon.

**Comment by DimitarTachev** [comment] 2018-01-26 16:16
@btulsi-ygrene @tomylee001001 

Changing the launchMode to `singleTop` or `singleTask` is changing the intent of an existing activity which wasn't handled by the NativeScript main activity.

We made an improvement which will fix the above-mentioned scenario by always providing the proper intent on application resume.

You could track the status of this pull request https://github.com/NativeScript/NativeScript/pull/5337 and update your nativescript-core-modules once the fix gets published.

**Comment by DimitarTachev** [comment] 2018-01-31 08:42
I'm closing the issue as the above-mentioned pull request was merged and the change is available in the `next` version of the NativeScript core modules.

**Closed by DimitarTachev** 2018-01-31 08:42 UTC
Labels: backlog, docs, question
