### ISSUE TITLE
 Configuration with name 'compile' not found.

### ISSUE THREAD

**Issue by mayureshjadhav** [NativeScript/push-plugin#170] opened 2018-01-02 07:13 UTC
Hi,

I am getting following error while running the application. 
```
FAILURE: Build failed with an exception.


* What went wrong:
A problem occurred configuring root project .
> Configuration with name 'compile' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

```
After doing a google, I found below link

[https://stackoverflow.com/questions/44867212/android-studio-gradle-errorconfiguration-with-name-compile-not-found](url)

I made the changes on the basis of that on both app.gradle and build.gradle files but received the different error message

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processF0F1F2F3F4F5F6F7F8F9F10F11F12F13DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.
```

Following are the plugins I am using

```
"nativescript-background-geolocation-lt": "^1.7.0",
    "nativescript-background-http": "^3.1.0",
    "nativescript-geolocation": "^4.2.2",
    "nativescript-google-maps-sdk": "^2.4.3",
    "nativescript-google-place-picker": "^1.0.1",
    "nativescript-push-notifications": "^0.2.0"
```
Platform:
```

"tns-android": {
      "version": "3.4.0"
    }
```

After doing a lot of research I found that nativescript-push-notifications having issues. Can you please help me to solve this issue?

Thank you.

**Comment by jogboms** [comment] 2018-01-02 08:52
@mayureshjadhav as a temporary fix, go to `platforms/android/build.gradle` and cut out this line `apply plugin: "com.google.gms.google-services"` at the bottom of the file. Then go to `platforms/android/app/build.gradle` and paste it at the bottom of the file there.

**Comment by mayureshjadhav** [comment] 2018-01-02 09:52
@jogboms Done that but getting following error


```
* What went wrong:
Execution failed for task ':app:processF0F1F2F3F4F5F6F7F8F9F10F11F12F13DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

```

**Comment by jogboms** [comment] 2018-01-03 08:02
@mayureshjadhav did you also follow what was described here https://github.com/NativeScript/push-plugin/issues/165#issuecomment-354615340?

A permanent fix is on the way tho.

**Comment by mayureshjadhav** [comment] 2018-01-03 08:22
Yes. I followed that but still getting the above error.

**Comment by jogboms** [comment] 2018-01-03 08:32
Thats a bit odd since i currently run my project applying those fixes. 
1. Edit the util.js within node_modules
2. move `apply plugin: "com.google.gms.google-services"` from `platforms/android/build.gradle` to `platforms/android/app/build.gradle`

You could also see #173

**Comment by lini** [comment] 2018-01-03 09:39
This issue should be fixed in the latest relase - https://github.com/NativeScript/push-plugin/releases/tag/v0.3.0

**Comment by dtopuzov** [comment] 2018-01-03 10:12
Close as duplicate of https://github.com/NativeScript/push-plugin/issues/173

**Closed by dtopuzov** 2018-01-03 10:12 UTC
