### ISSUE TITLE
An uncaught exception on sample-push-plugin

### ISSUE THREAD

**Issue by vchimev** [NativeScript/push-plugin#88] opened 2017-01-25 11:29 UTC
CC: @georgiwe, @AntonDobrev

Ths sample-push-plugin does not work with nativescript-push-notifications@0.1.0.

An uncaught Exception occurred:
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process org.nativescript.allsdk. Make sure to call FirebaseApp.initializeApp(Context) first.

App:
https://github.com/NativeScript/sample-push-plugin

Steps:
```shell
git clone git@github.com:NativeScript/sample-push-plugin.git
cd sample-push-plugin
tns run android
```
- tap on ENABLE NOTIFICATIONS

ADB log:
https://gist.github.com/vchimev/9c96477ef1b9f87e72af5c87e8392157

Screenshot:
![screen](https://cloud.githubusercontent.com/assets/12251337/22288590/44ce0b5c-e300-11e6-9fdf-4505256da5ce.png)

**Comment by AntonDobrev** [comment] 2017-01-25 13:10
@vchimev I am closing this as a duplicate of #80

**Closed by AntonDobrev** 2017-01-25 13:10 UTC
