### ISSUE TITLE
Couldn't get notification data on `launchEvent` for Android

### ISSUE THREAD

**Issue by Guatom** [NativeScript/push-plugin#137] opened 2017-08-09 17:01 UTC
Hey guys!

First of all, thanks for your work: it's been more than super useful for me.

I'm currently using `nativescript-push-notifications@^0.1.4` and the following TNS modules:

```
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 3.1.2           │ 3.1.3          │ Update available │
│ tns-core-modules │ 3.1.1           │ 3.1.1          │ Up to date       │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date       │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date       │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘
```

It works just OK for Android and iOS, but on Android I can't get the content of the notification when it arrives while the application is closed. The message arrives, the application starts, but I can't get the content of the notification, no matter what I try.

I tried using `on` from `application` before and after `platformNativeScriptDynamic().bootstrapModule(AppModule);`, and nothing:

I also tried using these ways:
* https://github.com/NativeScript/push-plugin/issues/32
* https://github.com/NativeScript/push-plugin/issues/45
* https://github.com/NativeScript/push-plugin#handling-mixed-messages (applying `launchEvent` instead of `resumeEvent`; the event gets triggered but `android` only contains `constructor`).

Here's my `AndroidManifest.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools"
	package="__PACKAGE__"
	android:versionCode="1"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>Ï

	<application
		tools:replace="allowBackup"
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize"
			android:screenOrientation="sensorPortrait">

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />

				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
</manifest>
```

Any ideas?

Best regards and thanks again.

**Comment by Guatom** [comment] 2017-09-21 22:08
Is this working for someone using recent versions of NativeScript? A working repository would be useful for me.

**Comment by EwelinaLuiza** [comment] 2017-10-27 12:40
I have the same problem. Any update available?

**Comment by EwelinaLuiza** [comment] 2017-10-31 11:42
It works for me now. You have to retrieve value by key name e.g.
```
if (args.android) {
        var act = args.android;
        var intent = act.getIntent();
        var extras = intent.getExtras();
        let message = extras.getString("MESSAGE");
    };
```

**Comment by Guatom** [comment] 2017-10-31 11:49
I haven't made recent tests, but almost three months ago that code threw a void object in `var extras = intent.getExtras();`. But it's a good thing to know that it's working for someone, there must be something weird in my code. @EwelinaLuiza, which versions are you using?

**Comment by EwelinaLuiza** [comment] 2017-10-31 13:09
@Guatom I'm currently using 3.3.0 version (nativescript/tns-core-modules/ tns-android). I worked with 3.2.0 too and had the same behaviour. In Chrome debugger object seemed to be void, but `extras.getString("MESSAGE") ` returned value. At first I used code from the readme site
```
application.on(application.resumeEvent, function(args) {
    if (args.android) {
        var act = args.android;
        var intent = act.getIntent();
        var extras = intent.getExtras();
        if (extras) {
             for (var key in extras) {
                 console.log(key + ' -> ' + extras[key]);
            }
        }
    }
});
```
This code doesn't return any value. I had to use specific name like this:` extras.getString("MESSAGE")`

I had problem with resumeEvent too, which returned null as `intent.getExtras()` or was not fired at all. This was because I used my custom acitvity instead of NativeScriptActivity in AndroidManifest.xml and `launchMode="singleTop"`. I had to use `            intent.addFlags(android.content.Intent.FLAG_ACTIVITY_NO_HISTORY);` and override `protected onNewIntent(intent: android.content.Intent): void ` in the activity to extract data from notification.

Currently both launchEvent/resumeEvent work for me.

**Comment by Guatom** [comment] 2017-10-31 13:25
Thanks a lot @EwelinaLuiza! I'll give it a try. I also had problems with a custom Activity, but then noticed that it was not really needed.

**Comment by NickIliev** [comment] 2018-02-07 13:32
@Guatom @EwelinaLuiza 
The issue is a known bug but the good news is that the issue is already resolved and the fix is included in the next version of `tns-core-modules`. More details [here](https://github.com/NativeScript/NativeScript/issues/5377#issuecomment-363337118).

**Closed** 2018-02-07 13:32 UTC
Labels: os: android
