### ISSUE TITLE
 How do I get data when resume like Android in 'IOS'?

### ISSUE THREAD

**Issue by seohangyu** [NativeScript/push-plugin#154] opened 2017-12-12 10:25 UTC
application.on(application.resumeEvent, function(args) {
 if (args.android) {
    var act = args.android;
    var intent = act.getIntent();
    var extras = intent.getExtras();
    if (extras) {
       // for (var key in extras) {
       //     console.log(key + ' -> ' + extras[key]);
       // }
       var msg = extras.get('someKey'); 
    }
   } else if(args.ios) {
       var act = args.ios;
      **// What should I do in IOS?**
   }
});

This is an Android example.
What should I do in IOS?

**Comment by lini** [comment] 2017-12-15 12:04
duplicate of #156

**Closed by lini** 2017-12-15 12:04 UTC
