### ISSUE TITLE
Cannot find module error

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/push-plugin#65] opened 2016-11-18 17:08 UTC
Hello,  

I recently upgraded to NS 2.2 from 2.0 and now I am having trouble with loading the plugin in Android.  Everything works fine in iOS, but in android I am getting the following error:

**Error:  Cannot find module "nativescript-push-notifications"**

The error is in everlive.all.min.js line 339.  I am using Everilve SDK version 1.8.1

Here is what my package.json look like:

{
  "nativescript": {
    "id": "com.macfarlanegp.awlmobilenative"
  },
  "dependencies": {
    "moment": "2.14.1",
    "moment-timezone": "0.5.5",
    "nativescript-background-http": "2.4.0",
    "nativescript-email": "1.3.3",
    "nativescript-intl": "0.0.4",
    "nativescript-iqkeyboardmanager": "1.0.0",
    "nativescript-loading-indicator": "2.0.1",
    "nativescript-maskedinput": "0.0.3",
    "nativescript-pdf-view": "1.2.0",
    "nativescript-phone": "1.2.3",
    "nativescript-social-share": "1.3.1",
    "nativescript-telerik-ui": "1.5.0",
    "nativescript-touchid": "2.1.0",
    "tns-core-modules": "2.4.0",
    "nativescript-push-notifications": "0.0.15"
  },
  "devDependencies": {}
}

Any help is greatly appreciated.
Thank you.

**Comment by AntonDobrev** [comment] 2016-11-28 15:24
@dpdragnev Sorry for the late reply. This seems like a discrepancy in some of the runtime and dependency versions. 

May I suggest that you ensure upgrading to:
- the latest 2.3 version of NativeScript
- the latest 2.3 core NativeScript modules
- the plugin to 0.0.19

**Comment by dpdragnev** [comment] 2016-11-28 18:24
Thanks Anton,

Unfortunately, this did not help.  I am still getting the same error.  Do you have any other suggestions?

**Comment by AntonDobrev** [comment] 2016-11-29 09:47
@dpdragnev 

I managed to reproduce this issue in the NativeScript developer app (especially after syncing some changes).

Please ensure that you are running and testing the application package deployed on a device and not in the developer app. This should solve the problem you reported. 

Tested on:

Android 6.0 
NS run-time 2.3.0
NS modules 2.3.0 and 2.4.0 ( I can see you have in the package.json a reference to 2.4.0) 
JS SDK 1.8.1

**Comment by AntonDobrev** [comment] 2016-12-01 10:08
@dpdragnev It appears that the issue is reproducible for some cases. Please consider downgrading the JS SDK to 1.7.2 or 1.7.3, for example following the instructions from [here](http://docs.telerik.com/platform/backend-services/javascript/getting-started-javascript-sdk) or as provided in your private support case. 

I am closing this case, however, because it is not related to the plugin, it concerns the way the JS SDK utilizes the plugin.

**Closed by AntonDobrev** 2016-12-01 10:08 UTC
Labels: question
